### ISSUE TITLE
sendPort ArgumentError after document conflict

### ISSUE THREAD

**Issue by nblum37** [cofu-app/cbl-dart#34]
Hi,

thank you for this promising Couchbase Lite library. Looking already forward to it, when you reached the production state :)
I (maybe) found an issue, that occurs after the conflictResolver callback of the replicator was called. The conflictResolver is defined the following way (quite simple):

```
Future<Document> conflictResolver (String documentId, Document local,
    Document remote) async {
  print('Resolve conflict for asset $documentId');
  return remote;
}
```

and handed over as a callback in the replicator configuration before replicator creation. I attached some screenshots of the debugger output. I use the following packages

```
environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Couchbase
  cbl: ^0.4.1
  cbl_flutter: ^0.3.0+3
```

with Flutter 2.0.4, Dart 2.12.2, and Android API 29. To reproduce the error, I disconnect the Android emulator with the running app from the server, modify a document at the server, and re-establish the server connection. After a moment the conflictResolver is called successfully and a moment later the error is raised. Maybe you have some thought, whether it's really a library issue or it's me, abusing your framework.

Thank you :)

![Bildschirmfoto 2021-04-09 um 23 09 09](https://user-images.githubusercontent.com/82163574/114242044-7efd5400-998a-11eb-9703-3377ce982819.png)
![Bildschirmfoto 2021-04-09 um 23 08 24](https://user-images.githubusercontent.com/82163574/114242052-815fae00-998a-11eb-88cf-a3d84d922ca4.png)
![Bildschirmfoto 2021-04-09 um 23 08 09](https://user-images.githubusercontent.com/82163574/114242054-81f84480-998a-11eb-9b41-ba6792ff5359.png)
![Bildschirmfoto 2021-04-09 um 23 07 54](https://user-images.githubusercontent.com/82163574/114242056-8290db00-998a-11eb-953a-5e04b33577c6.png)

**Comment by blaugold** [comment]
Hey @nblum37, thanks for reporting this issue. This is a bug in the `cbl` package. The `Replicator` is not covered by tests yet (tracked in #6) and so more likely to have some bugs.

I'll try to publish a fix tomorrow.

**Comment by blaugold** [comment]
`cbl: ^0.4.1+1`, which contains the fix, has been published.

**Comment by nblum37** [comment]
Oh wow, that was fast! Thank you. I will directly check it out and give you some feedback :)

**Comment by nblum37** [comment]
It works well 👍 Nice!

**Comment by blaugold** [comment]
Glad to hear, and thanks for the feedback.

**Comment by blaugold** [comment]
@richard457 I think your issue is unrelated to this one, so I've created a new one over here: #630

**Comment by nblum37** [comment]
My issue was resolved with a fix from @blaugold 👍 Unfortunately, I cannot support here.
