### ISSUE TITLE
Remove Enterprise Edition features

### ISSUE THREAD

**Issue by blaugold** [cofu-app/cbl-dart#49]
These features are not tested and the distributed binaries are not built with EE features enabled. 

The EE might be supported at some later point.

**Comment by etiennelenhart** [comment]
Just to clarify: Are Enterprise features like Delta Sync currently not supported?

**Comment by blaugold** [comment]
Yes, EE features are not currently supported. The API exposes only some EE features, and those are not usable with the distributed binaries. The EE is not open source. How and when EE might be supported depends on whether Couchbase would be open to distributing the EE through this project, but I have contacted them regarding this.

**Comment by etiennelenhart** [comment]
Thanks for the quick answer. Makes sense.

**Comment by nblum37** [comment]
Hi,
was the encryption feature a EE feature as well in 0.6.0? We would like to start encrypting the database, as well. However, we are now afraid that this is only possible with the EE.

**Comment by blaugold** [comment]
Hey @nblum37,
I'm sorry to say that encryption was always an EE feature and not actually available 0.6.0.
