### ISSUE TITLE
Limitation: Background Data Sync on iOS and Android

### ISSUE THREAD

**Issue by floriancb** [cofu-app/cbl-dart#526]
I have been wondering whether there are any fundamental reasons which would not allow cbl-dart to sync data in the background. Was there just no need to get this implemented, or is there more to it?

Any feedback is much appreciated.

**Comment by blaugold** [comment]
This limitation is more of a missing feature than a limitation, when compared to the iOS SDK. Currently, the Dart SDK does not implement a similar integration with the app live cycle [described here](https://docs.couchbase.com/couchbase-lite/current/swift/replication.html#replication-status-and-app-life-cycle). There is nothing preventing you from running a replicator while the app is in the background.
