### ISSUE TITLE
Considerations about availability for use in a production environment

### ISSUE THREAD

**Issue by bysensa** [cofu-app/cbl-dart#55]
Hello. Is there any idea when the library can be used in the production environment? What are the current restrictions?

**Comment by blaugold** [comment]
The goal for `v1.0.0` is to align the API with Couchbase Lite for iOS/macOS. This will mean some breaking changes. 

Also, there is no query builder yet. Queries can be defined through [`N1QL` or JSON](https://pub.dev/documentation/cbl/latest/cbl/QueryDefinition-class.html) (which is what the query builder will use).

Windows and Linux are not supported yet, but that might be something for after `v1.0.0`.

If you're fine with some refactoring when upgrading, you should be able to use the library in production.
