### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) shortly after blob read interaction

### ISSUE THREAD

**Issue by nblum37** [cofu-app/cbl-dart#57]
Hi :)

I currently face an error, that I already tried to solve with various different workarounds. The base setup is (I guess) pretty simple. I add an image as a blob to a document and save it to the DB. It works to read the blob back and it's also replicated to the sync gateway and other users. However, if I restart the app, it gets the fatal crash message below, as soon as I want to interact with the blob again, even if I only want to only read the metadata. The crash does not happen exactly when reading the blob. Basically reading still works, however, the app crashes shortly afterward. So as soon as I did the reading I can't stop the app from crashing even though the reading of the blob itself was successful (Nevertheless if I only try to read the metadata). Maybe you have an idea. I attached two examples of crashes and the code used for writing and reading blobs. Really looking forward to your feedback!

Thank you :)

<img width="1821" alt="crash1" src="https://user-images.githubusercontent.com/82163574/120411655-735c5700-c355-11eb-8f8c-847ad5d426bf.png">
<img width="695" alt="source" src="https://user-images.githubusercontent.com/82163574/120411668-76efde00-c355-11eb-9711-e932a194b5f8.png">
<img width="1793" alt="crash2" src="https://user-images.githubusercontent.com/82163574/120411669-77887480-c355-11eb-88c9-11aa99483ef1.png">

**Comment by nblum37** [comment]
Sry, I forgot the used version in pubspec.yaml
  # Couchbase
  cbl: ^0.5.1
  cbl_flutter: ^0.3.1+1

**Comment by blaugold** [comment]
Hey @nblum37, I'm sorry you're having this issue. 

Could you try and move any metadata such as `comment` out of the `Blob`'s `Dict`s? The CouchbaseLite API is a bit unclear about whether it is a good idea to store metadata directly in `Blob`s. 

It also seems like CouchbaseLite expects a `Dict` which represents a  `Blob` not to be mutated. 

The API for `Blob`s is likely going to change to reflect those constraints.

**Comment by nblum37** [comment]
No problem. Thanks for the support! :)

I removed the metadata `comment`, cleaned everything, and tried again. Unfortunately with the same result. So the `Blob blob` variable is not changed after `createBlob`. I attached the resulting database entry.

![Bildschirmfoto 2021-06-02 um 11 24 20](https://user-images.githubusercontent.com/82163574/120455568-2b5d2480-c395-11eb-8e67-9e904ec513ab.png)

**Comment by nblum37** [comment]
So that was a good hint. Basically, later in the code another summary document is written to another DB. However, somehow even with breakpoints, it was not visible that the code runs until the next save command. Having that in mind, I was able to solve the bug by adding a
`blobMap.remove('@type');`
to the `getAttachments` function, to avoid a link to a blob, that does not exist in the other database.

**Comment by nblum37** [comment]
And it is possible to add metadata like comments directly to the blob. At least it's working for me

**Comment by blaugold** [comment]
I'm glad you could work it out. 😃
