### ISSUE TITLE
Build error: 'Arena' is exported from both 'package:cbl_ffi/src/utils.dart' and 'package:ffi/src/arena.dart'

### ISSUE THREAD

**Issue by vsutedjo** [cofu-app/cbl-dart#59]
### Issue description
I have a build issue with this package: _'Arena' is exported from both 'package:cbl_ffi/src/utils.dart' and 'package:ffi/src/arena.dart'_ when using either cbl or cbl_flutter.

### Minimal reproducible: 
I am on a windows PC, I created a new Flutter app (via flutter create), I added the package (cbl or cbl_flutter, this happens to both) into pubspec.yaml. This compiles without issues as expected. 

As soon as I add `import 'package:cbl/cbl.dart';` or respective line for cbl_flutter into any dart file, it will fail to build with the following message:
`/C:/SDKs/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cbl_ffi-0.5.1/lib/cbl_ffi.dart:1:1: Error: 'Arena' is exported from both 'package:cbl_ffi/src/utils.dart' and 'package:ffi/src/arena.dart'.
export 'package:ffi/ffi.dart';
^`

### Environment
flutter doctor:

[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.985], locale en-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)

A simple fix would probably be just renaming the internal Arena class or hiding the class when exporting, if that is used only internally anyway? A quick response or workaround would be appreciated. Thanks!

**Comment by blaugold** [comment]
Hey @vsutedjo, thanks for reporting this issue.

`ffi` added `Arena` in `1.1.0` and `cbl_ffi` is reexporting `ffi` together with its implementation of `Arena`, which is causing the name clash. 

Until this is fixed, pinning `ffi` to an earlier version should work:
```yaml
dependency_overrides:
  ffi: 1.0.0
```

**Comment by blaugold** [comment]
A release with a fix for this issue has been published:
```yaml
cbl: ^0.6.0
cbl_flutter: ^0.4.0
```
