### ISSUE TITLE
[cbl_flutter] port `tool/install_binaries.sh` to dart

### ISSUE THREAD

**Issue by blaugold** [cofu-app/cbl-dart#62]
`cbl_flutter` currently uses a bash script to install the binaries from `cbl_native`. We should port this script to dart so that it can be used on all platforms.

**Comment by natgross** [comment]
If the entire problem is bash on Windows, how about trying Git bash? I have it installed on my Windows machine and have used it in the past to run bash scripts. You might want to give it a spin from https://gitforwindows.org/.
I can try it as well, but I would need the script and instructions from which dir to run it from, as well as expected dir structure.

**Comment by blaugold** [comment]
Thanks for that hint. Git for Windows is a required dependency for Flutter anyway, so we can assume it's available.

**Comment by blaugold** [comment]
Closed by #63.

**Comment by natgross** [comment]
Happily report **v0.4.0+1** working ok on Windows.
