### ISSUE TITLE
The library not working on windows

### ISSUE THREAD

**Issue by AfricanDev** [cofu-app/cbl-dart#64]
cbl_ffi-0.5.1/lib/cbl_ffi.dart(1,1): error GA3817E87: 'Arena' is exported from both 'package:cbl_ffi/src/utils.dart' and 'package:ffi/src/arena.dart'. [E:\demos\flipper-new\flipper\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by blaugold** [comment]
Hi @AfricanDev,

Please make sure you use `cbl: ^0.6.0`. This issue has been fixed in that release (#59).

**Comment by AfricanDev** [comment]
Now getting this Unhandled Exception: Unsupported operation: This platform is not supported.
#0      flutterLibraries
package package:cbl_flutter/cbl_flutter.dart:19

**Comment by AfricanDev** [comment]
I am using windows 10

**Comment by AfricanDev** [comment]
and on android getting this problem occurred configuring project ':cbl_flutter'.
> NDK at C:\Users\Sone\AppData\Local\Android\sdk\ndk\21.1.6352462 did not have a source.properties file

**Comment by blaugold** [comment]
Currently, only iOS, macOS and Android are supported by `cbl_flutter`. You can build for Android on Windows, though.

**Comment by AfricanDev** [comment]
any plan in supporting windows?

**Comment by blaugold** [comment]
In the long term, yes. Probably once Flutter for Windows is stable.

**Comment by blaugold** [comment]
Regarding the build issue on Android, maybe [this](https://stackoverflow.com/questions/64372383/ndk-at-library-android-sdk-ndk-bundle-did-not-have-a-source-properties-file) stackoverflow can help.

**Comment by AfricanDev** [comment]
Yes followed the article but at the end now I get this on android Unhandled Exception: Invalid argument(s): Failed to lookup symbol (undefined symbol: CBLDatabase_PerformMaintenance)

**Comment by blaugold** [comment]
Are you using the latest versions?

```yaml
cbl: ^0.6.0
cbl_flutter: ^0.4.0+1
```

**Comment by blaugold** [comment]
Please reopen if this issue has not been resolved.
