### ISSUE TITLE
install_binaries.sh on macOS

### ISSUE THREAD

**Issue by etiennelenhart** [cofu-app/cbl-dart#65]
Hey, I just discovered your awesome library!

I found a small issue though that currently prevents installing `cbl_flutter` with CocoaPods. It seems that the issue was introduced with the recent change to support install_binaries.sh on Windows #63.
I was able to fix the issue by making a change in line 32 from `pkgDirSys=pkgDir` to `pkgDirSys=$pkgDir`. (Note the missing `$`.)
Otherwise I was getting an error at the `flutter pub get` line concerning the `tmp` package.

I currently don't have the time for a proper pull request, but I hope this should be a rather small fix on your side.

**Comment by blaugold** [comment]
The fix has been published in version `0.4.0+2` of `cbl_flutter`.

**Comment by etiennelenhart** [comment]
Wow, that was quick. Thank you!
