### ISSUE TITLE
compatibility with another couchbase client 

### ISSUE THREAD

**Issue by mehrdad-shokri** [cofu-app/cbl-dart#68]
hello, I have an app using couchbase with [this](https://pub.dev/packages/couchbase_lite) client. can I migrate my app from that lib to your library and keep the current database? To be more specific supposedly I find filename of stored database used for that library, and giving it as my database file to this lib would data be loaded correct?

**Comment by blaugold** [comment]
Hey @mehrdad-shokri, I haven't tried that, but it should be possible since the underlying implementation is the same.

**Comment by mehrdad-shokri** [comment]
Thanks for your reply. My app is in android so I just care for Android. Do both use C implementation?
Also can you hint a bit how to convert query builder to n1ql or json? Thank you

**Comment by blaugold** [comment]
> Do both use C implementation?

Yes, both are based on [couchbase-lite-core](https://github.com/couchbase/couchbase-lite-core).

> Also can you hint a bit how to convert query builder to n1ql or json?

The JSON syntax is not really meant to be written by humans. The query builder, for example, generates JSON syntax queries. I plan to implement the query builder API eventually (#7), just haven't gotten around to it yet. Is there any particular reason you want to migrate? If you can, it might be easier to wait until the query builder API is available.

If you give me a concrete example of query builder code, I can talk you through how to rewrite the query in N1QL.

**Comment by mehrdad-shokri** [comment]
@blaugold thanks for your reply. I'm considering migrating to this library because the mentioned library has outdated dependencies which prevent updating my other dependencies. Also, it doesn't support null safety(the latest commit is for Dec 2020)  
I'm in the process of migrating an app to null safety and updating all my dependencies to the latest version so they support null safety.  
One solution for me would be to fork that repo update dependency and upgrade the lib to null safety and another one would be to completely change my client to this lib. As I mentioned this app has Android clients so I really prefer to keep existing data.  

> If you give me a concrete example of query builder code, I can talk you through how to rewrite the query in N1QL.

I have a set of models and each model is represented as a dart class. I have a set a static methods on each model for selecting for example here's a query builder for selecting todos:  
 ```
  static Where selectTodoFields({Expression? andWhere}) {
    Expression where = Expression.property('type')
        .from(ALIAS)
        .equalTo(Expression.string(TYPE));
    if (andWhere != null) {
      where = where.and(andWhere);
    }
    return QueryBuilder.select([
      SelectResult.expression(Meta.id.from(ALIAS)).as('id'),
      SelectResult.expression(Expression.property('uuid').from(ALIAS))
          .as('uuid'),
      SelectResult.expression(Expression.property('title').from(ALIAS))
          .as('title'),
      SelectResult.expression(Expression.property('done').from(ALIAS))
          .as('done'),
      SelectResult.expression(Expression.property('dueDate').from(ALIAS))
          .as('dueDate'),
      SelectResult.expression(Expression.property('createdAt').from(ALIAS))
          .as('createdAt'),
      SelectResult.expression(Expression.property('dueTime').from(ALIAS))
          .as('dueTime'),
      SelectResult.expression(Expression.property('endDate').from(ALIAS))
          .as('endDate'),
      SelectResult.expression(Expression.property('projectId').from(ALIAS))
          .as('projectId'),
      SelectResult.expression(Expression.property('priority').from(ALIAS))
          .as('priority'),
      SelectResult.expression(Expression.property('note').from(ALIAS))
          .as('note'),
      SelectResult.expression(Expression.property('userId').from(ALIAS))
          .as('userId'),
      SelectResult.expression(Expression.property('subTasks').from(ALIAS))
          .as('subTasks'),
      SelectResult.expression(Expression.property('tagIds').from(ALIAS))
          .as('tagIds'),
      SelectResult.expression(Expression.property('repeatInterval').from(ALIAS))
          .as('repeatInterval'),
      SelectResult.expression(Expression.property('repeatType').from(ALIAS))
          .as('repeatType'),
      SelectResult.expression(Expression.property('doneRepeat').from(ALIAS))
          .as('doneRepeat')
    ]).from(Constants.DB_NAME, as: ALIAS).where(where);
  }
```
now I have 2 selectors which execute that query(1 passes another where to the method) and call ``fromResult`` to convert Result to my ``Todo`` model(which basically casts result to ``Map`` and read specified keys to load model)  

```lang:dart
static Future<List<Todo>> allTodos() async {
    List<Reminder> reminders = await Reminder.allReminders();
    ResultSet resultSet = await selectTodoFields().execute();
    return resultSet
        .allResults()
        .map((Result result) => Todo.fromResult(result))
        .map((todo) {
      todo.reminders =
          reminders.where((reminder) => reminder.todoId == todo.id).toList();
      return todo;
    }).toList();
  }

  static Future<List<Todo>> projectTodos(String projectId) async {
    List<Reminder> reminders = await Reminder.allReminders();
    ResultSet resultSet = await selectTodoFields(
            andWhere: Expression.property('projectId')
                .from(ALIAS)
                .equalTo(Expression.string(projectId)))
        .execute();
    return resultSet
        .allResults()
        .map((Result result) => Todo.fromResult(result))
        .map((todo) {
      todo.reminders =
          reminders.where((reminder) => reminder.todoId == todo.id).toList();
      return todo;
    }).toList();
  }
```

**Comment by blaugold** [comment]
This is the basic query to load the `id` + all properties of all `Todo`s:

```sql
SELECT meta(todo).id AS id, todo AS properties
FROM db AS todo
WHERE todo.type = 'Todo'
```

`db` in the `FROM` clause is chosen arbitrarily, since Couchbase Lite only supports a single bucket/database. Selecting `todo AS properties`, selects all the document properties and makes them available in the `Result` under `properties`. To select only a subset of the document properties, you would write something like `SELECT meta(todo).id AS id, todo.uuid AS uuid, todo.title AS title, ...`

To filter `Todo`s by `projectId`, you would change the `WHERE` clause of the query above to `WHERE todo.type = 'Todo' AND todo.projectId = $PROJECT_ID`. `$PROJECT_ID` is a parameter that you set with `Query.setParamters` before calling `execute` on the [`Query`](https://pub.dev/documentation/cbl/latest/cbl/Query-class.html).

To pull the selected columns out of a `Result` by alias, use [`Result.dict`](https://pub.dev/documentation/cbl/latest/cbl/Result/dict.html).

**Comment by mehrdad-shokri** [comment]
@blaugold Thank you for your reply. I don't understand how to construct this query:  
```
SELECT meta(todo).id AS id, todo AS properties
FROM db AS todo
WHERE todo.type = 'Todo'
```
Do I need to call Query() with this query string as the constructor argument?

**Comment by blaugold** [comment]
Here is how to create a query:
```dart
final db = ...;
final query = await db.query(N1QLQuery('''
  SELECT meta(todo).id AS id, todo AS properties
  FROM db AS todo
  WHERE todo.type = 'Todo'
'''));
```
